# configuration.yaml
application:
  port: 8000
  hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
database:
  host: "127.0.0.1"
  port: 5432
  username: "frank"
  password: "root"
  database_name: "newsletter"