# configuration.yaml
application:
  port: 8000
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
database:
  host: "127.0.0.1"
  port: 5432
  username: "frank"
  password: "root"
  database_name: "newsletter"